import type { Leader, Member, ClubEvent, GalleryItem } from './types'

const PH = 'https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=400&h=400&fit=crop&crop=faces'

export const leaders: Leader[] = [
   {
    id: 'L1',
    name: 'Dr. B Santhosh Kumar',
    position: 'HOD-CSE & Coordinator',
    photo: 'https://cdnintech.com/media/author/330426/1763460266/profile/image1.jpg',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: 'Faculty',
    linkedin: 'https://www.linkedin.com/in/drbskumar/',
    github: '',
    email: 'bsanthosh.csegnit@gniindia.org',
  },
  {
    id: 'L2',
    name: 'Dr. B Ranjitha ',
    position: 'Faculty Coordinator 1',
    photo: '/Team Members/IMG_2172.JPG',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: 'Faculty',
    linkedin: '',
    github: '',
    email: 'ranjithab.csegnit@gniindia.org',
  },
  {
    id: 'L3',
    name: 'Mr. K Vigneshwar',
    position: 'Faculty Coordinator 2',
    photo: '/Team Members/IMG_1887.JPG',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: 'Faculty',
    linkedin: '',
    github: '',
    email: 'kvigneshwar.gnit@gniindia.org',
  },
  {
    id: 'L4',
    name: 'Newton Adhikari',
    position: 'President',
    photo: '/Team Members/newton.png',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: '4th Year',
    linkedin: 'https://www.linkedin.com/in/newton-adhikari',
    github: '',
    email: '23831a05e5@gniindia.org',
  },
  {
    id: 'L5',
    name: 'Kishore Voodi',
    position: 'Vice President',
    photo: '/Team Members/kishor.jpeg',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: '4th Year',
    linkedin: 'https://www.linkedin.com/in/kishore-voodi-7b2410285',
    github: '',
    email: '23831a05k0@gniindia.org',
  },
  {
    id: 'L6',
    name: 'Shreeirth Tapelkar',
    position: 'Secretary (Boys)',
    photo: '/Team Members/shree.jpeg',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: '4th Year',
    linkedin: 'https://www.linkedin.com/in/bishal-bista-952630306',
    github: '',
    email: '23831a05g3@gniindia.org',
  },
  {
    id: 'L7',
    name: 'Puspa Bhandari',
    position: 'Secretary (Girls)',
    photo: '/Team Members/puspa.jpeg',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: '4th Year',
    linkedin: '',
    github: '',
    email: '23831a05l5@gniindia.org',
  },
  {
    id: 'L8',
    name: 'Nitesh Kushwaha',
    position: 'Technical Head',
    photo: '/Team Members/nitesh.png',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: '4th Year',
    linkedin: 'https://www.linkedin.com/in/nitesh-kushwaha',
    github: '',
    email: '23831a05k8@gniindia.org',
  },
  {
    id: 'L9',
    name: 'Yepuri Neha',
    position: 'Event Head',
    photo: '/Team Members/neha.jpeg',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: '4th Year',
    linkedin: '',
    github: '',
    email: '23831a05k5@gniindia.org',
  },
  {
    id: 'L10',
    name: 'Pranshu Choudhary',
    position: 'Media Head',
    photo: '/Team Members/pranshu.jpeg',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: '4th Year',
    linkedin: '',
    github: '',
    email: '23831a05e4@gniindia.org',
  },
  {
    id: 'L11',
    name: 'Bishal Bista',
    position: 'Design Head',
    photo: '/Team Members/bishal.jpeg',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: '4th Year',
    linkedin: '',
    github: '',
    email: '23831a05l4@gniindia.org',
  },
  {
    id: 'L12',
    name: 'S.Vishwasree',
    position: 'Documentation Head',
    photo: '/Team Members/viswa.JPG',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: '4th Year',
    linkedin: '',
    github: '',
    email: '23831a05g9@gniindia.org',
  },
  {
    id: 'L13',
    name: 'Praveen Reddy',
    position: 'Student Coordinator',
    photo: '/Team Members/pravin.jpeg',
    department: 'Computer Science & Engineering',
    branch: 'CSE',
    year: '4th Year',
    linkedin: '',
    github: '',
    email: '23831a05h5@gniindia.org',
  },
]

export const members: Member[] = [
{ id: 'M1', name: 'Newton Adhikari', roll: '23831A05E5', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M2', name: 'Govind Sah', roll: '23831A05E2', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M3', name: 'Pranshu Choudhary', roll: '23831A05E4', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M4', name: 'Pothuganti Viswanadh', roll: '23831A05E3', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M5', name: 'Rachapally Soumya', roll: '23831A05E6', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M6', name: 'Ranabothu Manogna', roll: '23831A05E7', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M7', name: 'Ravilla Srinivasulu', roll: '23831A05E8', branch: 'CSE', year: '4th Year', role: 'Event Coordinator Head', photo: '' },
{ id: 'M8', name: 'Rayanaboina Manisha', roll: '23831A05E9', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M9', name: 'Sai Varshith', roll: '23831A05F2', branch: 'CSE', year: '4th Year', role: 'Logistic Head', photo: '' },
{ id: 'M10', name: 'Sama Usha Reddy', roll: '23831A05F5', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M11', name: 'Bishal Bista', roll: '23831A05L4', branch: 'CSE', year: '4th Year', role: 'Student Representative (Boys)', photo: '' },
{ id: 'M12', name: 'Vishwasree', roll: '23831A05G9', branch: 'CSE', year: '4th Year', role: 'Student Representative (Girls)', photo: '' },
{ id: 'M13', name: 'Nitesh Kushwaha', roll: '23831A05K8', branch: 'CSE', year: '4th Year', role: 'Technical Head', photo: '' },
{ id: 'M14', name: 'Varansh Jain', roll: '23831A05J7', branch: 'CSE', year: '4th Year', role: 'Social Media Head', photo: '' },
{ id: 'M15', name: 'Yepuri Neha', roll: '23831A05K5', branch: 'CSE', year: '4th Year', role: 'Promotion Head', photo: '' },
{ id: 'M16', name: 'Theluri Praveen Reddy', roll: '23831A05H6', branch: 'CSE', year: '4th Year', role: 'Promotion Head', photo: '' },
{ id: 'M17', name: 'Vemula Vigneshwari', roll: '23831A05J8', branch: 'CSE', year: '4th Year', role: 'Content & Documentation Head', photo: '' },
{ id: 'M18', name: 'Jangam Ashwik', roll: '24835A0512', branch: 'CSE', year: '4th Year', role: 'Designer Head', photo: '' },
{ id: 'M19', name: 'Chandel Sathish Kumar', roll: '23831A0533', branch: 'CSE', year: '4th Year', role: 'Editor & Photographer Head', photo: '' },
{ id: 'M20', name: 'Rohith', roll: '23831A05H2', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M21', name: 'T Nandini', roll: '23831A05H1', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M22', name: 'Javaji Vijaykumar', roll: '23831A05H3', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M23', name: 'Tamburu Sree Chandana', roll: '23831A05H4', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M24', name: 'Tejavath Mahesh', roll: '23831A05H5', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M25', name: 'Thokala Manideep', roll: '23831A05H7', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M26', name: 'Thopula Varun Sai', roll: '23831A05H8', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M27', name: 'Togapuram Abhiram Kumar', roll: '23831A05H9', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M28', name: 'Tondolu Manisha', roll: '23831A05J0', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M29', name: 'Ugude Vaishnavi', roll: '23831A05J1', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M30', name: 'Uppari Smrithi Raj', roll: '23831A05J2', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M31', name: 'U Anil Kumar', roll: '23831A05J3', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M32', name: 'Vankudothu Vaishnavi', roll: '23831A05J6', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M33', name: 'Vilapara Supraja', roll: '23831A05J9', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M34', name: 'Vislavath Ramesh', roll: '23831A05K0', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M35', name: 'Vithanala Jahnavi', roll: '23831A05K1', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M36', name: 'Voodi Kishore', roll: '23831A05K2', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M37', name: 'Yasa Sreya', roll: '23831A05K4', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M38', name: 'K B Varun Kumar Reddy', roll: '23831A05K6', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M39', name: 'Pushpa Bhandari', roll: '23831A05L5', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M40', name: 'Mudupu Sravya Reddy', roll: '24835A0521', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M41', name: 'Mujja Vamshi', roll: '24835A0522', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M42', name: 'Pusala Bharath', roll: '24835A0523', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M43', name: 'Putti Srinath', roll: '24835A0524', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M44', name: 'Sreeramoju Akash Tej', roll: '24835A0525', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
{ id: 'M45', name: 'Thota Nikhitha', roll: '24835A0526', branch: 'CSE', year: '4th Year', role: 'Member', photo: '' },
]


export const events: ClubEvent[] = [
  {
    
  id: 'E1',
  title: 'Meta Storm 2026',
  slug: 'meta-storm-2026',
  banner: '/Metastrom/Poster.jpeg',
  description:
    'Meta Storm 2026 is the flagship technical fest organized by the HackerRank Club, Department of Computer Science & Engineering, GNIT. The event brings together students from various disciplines to participate in coding challenges, AI/ML competitions, technical quizzes, poster presentations, gaming tournaments, project exhibitions, and innovation-driven activities. Meta Storm aims to foster creativity, collaboration, leadership, and technical excellence among students.',

  date: '2026-02-09',
  venue: 'Guru Nanak Institute of Technology (GNIT), Ibrahimpatnam, Hyderabad',
  status: 'completed',
  registrationLink: '#',

  schedule: [
    { time: '09:00 AM', activity: 'Inauguration Ceremony' },
    { time: '10:00 AM', activity: 'Coding Challenge Round 1' },
    { time: '11:30 AM', activity: 'Technical Quiz Competition' },
    { time: '01:00 PM', activity: 'Lunch Break' },
    { time: '02:00 PM', activity: 'Poster Presentation & Project Showcase' },
    { time: '03:30 PM', activity: 'AI & Machine Learning Challenge' },
    { time: '05:00 PM', activity: 'Day 1 Wrap-up' },

    { time: '09:30 AM (Day 2)', activity: 'Hackathon & Innovation Sprint' },
    { time: '11:00 AM (Day 2)', activity: 'E-Sports Tournament' },
    { time: '01:00 PM (Day 2)', activity: 'Lunch Break' },
    { time: '02:00 PM (Day 2)', activity: 'Final Presentations & Judging' },
    { time: '04:00 PM (Day 2)', activity: 'Prize Distribution Ceremony' },
    { time: '05:00 PM (Day 2)', activity: 'Closing Ceremony' },
  ],

  speakers: [
    {
      name: 'Dr. B Santhosh Kumar',
      role: 'Coordinator',
      bio: 'Coordinator of HackerRank Club and Head Advisor for Meta Storm 2026.',
    },
    {
      name: 'Dr. B. Ranjitha',
      role: 'Faculty Coordinator',
      bio: 'Faculty Coordinator of HackerRank Club and mentor for Meta Storm 2026.',
    },
    {
      name: 'Mr. K. Vigneshwar',
      role: ' Faculty Coordinator',
      bio: 'Guided students in organizing technical and innovation-driven activities.',
    },
    {
      name: 'Industry Expert Panel',
      role: 'Guest Speakers',
      bio: 'Professionals from software, AI, and technology sectors who interacted with participants.',
    },
  ],

  coordinators: [
    {
      name: 'Newton Adhikari',
      contact: '+91 9398350151',
    },
    {
      name: 'Nitesh Kushwaha',
      contact: '+91 6356355608',
    },
    {
      name: 'Bishal Bista',
      contact: '+91 7780109232',
    },
    {
      name: 'Vishwasree',
      contact: '+91 7702904644',
    },
  ],

  gallery: [
    '/Metastrom/IMG_1846.JPG',
    '/Metastrom/IMG_1847.JPG',
    '/Metastrom/IMG_1848.JPG',
    '/Metastrom/IMG_1849.JPG',
    '/Metastrom/IMG_1850.JPG',
  ],

  sponsors: [
    'GNIT',
    'Department of CSE',
    'HackerRank Club',
    'Student Activity Center',
  ],
  },
  {
  id: 'E2',
  title: 'CreateX 2026',
  slug: 'createx-2026',
  banner: '/Metastrom/CreateX Poster.jpeg',

  description:
    'CreateX 2026 is a flagship creativity and innovation event organized by the HackerRank Club, CSE Department, GNIT. The event encourages students to showcase innovative ideas, startup concepts, UI/UX designs, technical solutions, creative presentations, and entrepreneurial thinking. Participants collaborate, brainstorm, and build impactful solutions to real-world challenges.',

  date: '2026-08-10',
  venue: 'Guru Nanak Institute of Technology (GNIT), Hyderabad',

  status: 'completed',

  registrationLink: '#',

  schedule: [
    {
      time: '09:00 AM',
      activity: 'Opening Ceremony & Introduction to CreateX',
    },
    {
      time: '10:00 AM',
      activity: 'Idea Pitching Round',
    },
    {
      time: '11:30 AM',
      activity: 'Innovation & Design Thinking Workshop',
    },
    {
      time: '01:00 PM',
      activity: 'Lunch Break',
    },
    {
      time: '02:00 PM',
      activity: 'Prototype Development Session',
    },
    {
      time: '03:30 PM',
      activity: 'Mentoring & Review Session',
    },
    {
      time: '05:00 PM',
      activity: 'Day 1 Wrap-up',
    },
    {
      time: '10:00 AM (Day 2)',
      activity: 'Final Project Presentation',
    },
    {
      time: '12:00 PM (Day 2)',
      activity: 'Judging & Evaluation',
    },
    {
      time: '02:00 PM (Day 2)',
      activity: 'Award Ceremony',
    },
  ],

  speakers: [
    {
      name: 'Dr. B Santhosh Kumar',
      role: 'Coordinator',
      bio: 'Guiding students in innovation, leadership, and entrepreneurship.',
    },
    {
      name: 'Dr. B. Ranjitha',
      role: 'Faculty Coordinator',
      bio: 'Mentor for student innovation and creative projects.',
    },
    {
      name: 'Mr. K. Vigneshwar',
      role: 'Faculty Coordinator',
      bio: 'Encourages practical implementation of innovative ideas.',
    },
  ],

  coordinators: [
    {
      name: 'Newton Adhikari',
      contact: '+91 9398350151',
    },
    {
      name: 'Nitesh Kushwaha',
      contact: '+91 6356355608',
    },
    {
      name: 'Bishal Bista',
      contact: '+91 7780109232',
    },
  ],

  gallery: [],

  sponsors: [
    'GNIT',
    'Department of CSE',
    'HackerRank Club',
    'Innovation Cell',
  ],
},
  {
    id: 'E5',
    title: 'Hackathon GNIT 2025',
    slug: 'hackathon-gnit-2025',
    banner: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=600&fit=crop',
    description: 'A 24-hour hackathon with 200+ participants and 40+ teams. Themes included healthcare, education, and sustainability.',
    date: '2025-04-12',
    venue: 'GNIT Main Auditorium',
    status: 'completed',
    registrationLink: '#',
    schedule: [
      { time: '09:00 AM', activity: 'Opening Ceremony' },
      { time: '10:00 AM', activity: 'Coding Begins' },
      { time: '10:00 AM (Day 2)', activity: 'Final Submissions' },
    ],
    speakers: [{ name: 'Dr. Rajesh Kumar', role: 'Coordinator', bio: 'Hackathon organizer.' }],
    coordinators: [{ name: 'Vikram Patel', contact: '+91 98765 43215' }],
    gallery: [
      'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1531497865144-0464ef8fb9a9?w=600&h=400&fit=crop',
    ],
    sponsors: ['TechCorp', 'CodeNation', 'DevHub'],
  },
  {
    id: 'E6',
    title: 'Industry Talk: Future of Cloud',
    slug: 'industry-talk-cloud-2025',
    banner: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&h=600&fit=crop',
    description: 'An insightful talk by industry leaders on the future of cloud computing, serverless architecture, and edge computing.',
    date: '2025-10-15',
    venue: 'Seminar Hall, IT Block',
    status: 'completed',
    registrationLink: '#',
    schedule: [{ time: '04:00 PM', activity: 'Talk by Industry Expert' }],
    speakers: [{ name: 'Mr. Anil Kumar', role: 'Cloud Architect, AWS', bio: '15+ years in cloud infrastructure.' }],
    coordinators: [{ name: 'Riya Nair', contact: '+91 98765 43216' }],
    gallery: [],
    sponsors: ['AWS', 'Azure'],
  },
]

export const galleryItems: GalleryItem[] = [
 { id: 'G1', title: 'Meta Strom 2026 - Opening Ceremony', type: 'photo', url: '/Metastrom/IMG_1846.JPG', event: 'Meta Strom 2026' },
{ id: 'G2', title: 'Meta Strom 2026 - Registration Desk', type: 'photo', url: '/Metastrom/IMG_1853.JPG', event: 'Meta Strom 2026' },
{ id: 'G3', title: 'Meta Strom 2026 - Inauguration', type: 'photo', url: '/Metastrom/IMG_1865.JPG', event: 'Meta Strom 2026' },
{ id: 'G4', title: 'Meta Strom 2026 - Faculty Address', type: 'photo', url: '/Metastrom/IMG_1867.JPG', event: 'Meta Strom 2026' },
{ id: 'G5', title: 'Meta Strom 2026 - Participant Gathering', type: 'photo', url: '/Metastrom/IMG_1973.JPG', event: 'Meta Strom 2026' },
{ id: 'G6', title: 'Meta Strom 2026 - Coding Round', type: 'photo', url: '/Metastrom/IMG_1977.JPG', event: 'Meta Strom 2026' },
{ id: 'G7', title: 'Meta Strom 2026 - Team Discussion', type: 'photo', url: '/Metastrom/IMG_1993.JPG', event: 'Meta Strom 2026' },
{ id: 'G8', title: 'Meta Strom 2026 - Technical Session', type: 'photo', url: '/Metastrom/IMG_2178.JPG', event: 'Meta Strom 2026' },
{ id: 'G9', title: 'Meta Strom 2026 - Workshop Activity', type: 'photo', url: '/Metastrom/IMG_2773.JPG', event: 'Meta Strom 2026' },
{ id: 'G10', title: 'Meta Strom 2026 - Competition Round', type: 'photo', url: '/Metastrom/IMG_2884.JPG', event: 'Meta Strom 2026' },
{ id: 'G11', title: 'Meta Strom 2026 - Innovation Showcase', type: 'photo', url: '/Metastrom/IMG_2942.JPG', event: 'Meta Strom 2026' },
{ id: 'G12', title: 'Meta Strom 2026 - Student Participation', type: 'photo', url: '/Metastrom/IMG_2943.JPG', event: 'Meta Strom 2026' },
{ id: 'G13', title: 'Meta Strom 2026 - Project Presentation', type: 'photo', url: '/Metastrom/IMG_4199.JPG', event: 'Meta Strom 2026' },
{ id: 'G14', title: 'Meta Strom 2026 - Expert Evaluation', type: 'photo', url: '/Metastrom/IMG_4215.JPG', event: 'Meta Strom 2026' },
{ id: 'G15', title: 'Meta Strom 2026 - Networking Session', type: 'photo', url: '/Metastrom/IMG_4219.JPG', event: 'Meta Strom 2026' },
{ id: 'G16', title: 'Meta Strom 2026 - Interactive Discussion', type: 'photo', url: '/Metastrom/IMG_4233.JPG', event: 'Meta Strom 2026' },
{ id: 'G17', title: 'Meta Strom 2026 - Team Collaboration', type: 'photo', url: '/Metastrom/IMG_4342.JPG', event: 'Meta Strom 2026' },
{ id: 'G18', title: 'Meta Strom 2026 - Event Highlights', type: 'photo', url: '/Metastrom/IMG_4540.JPG', event: 'Meta Strom 2026' },
{ id: 'G19', title: 'Meta Strom 2026 - Final Round', type: 'photo', url: '/Metastrom/IMG_4792.JPG', event: 'Meta Strom 2026' },
{ id: 'G20', title: 'Meta Strom 2026 - Award Ceremony', type: 'photo', url: '/Metastrom/IMG_4837.JPG', event: 'Meta Strom 2026' },
{ id: 'G21', title: 'Meta Strom 2026 - Winners Celebration', type: 'photo', url: '/Metastrom/IMG_4853.JPG', event: 'Meta Strom 2026' },
{ id: 'G22', title: 'Meta Strom 2026 - Group Photograph', type: 'photo', url: '/Metastrom/IMG_4868.JPG', event: 'Meta Strom 2026' },
{ id: 'G23', title: 'Meta Strom 2026 - Closing Ceremony', type: 'photo', url: '/Metastrom/IMG_4910.JPG', event: 'Meta Strom 2026' },

]

export const sponsors = [
  { name: 'Guru Nanak Institute of Technology', logo: 'GN' },
  { name: 'Department of Computer Science & Engineering', logo: 'CS' },
  { name: 'HackerRank Club', logo: 'HR' },
  { name: 'Student Activity Center', logo: 'SA' },
  { name: 'Innovation Cell', logo: 'IC' },
  { name: 'Training & Placement Cell', logo: 'TP' },
  { name: 'GNIT Alumni Association', logo: 'AA' },
  { name: 'GNIT Research Cell', logo: 'RC' },
  { name: 'Meta Storm', logo: 'MS' },
  { name: 'CreateX', logo: 'CX' },
]

export const clubStats = [
  { label: 'Members', value: 30, suffix: '+' },
  { label: 'Events Conducted', value: 2, suffix: '+' },
  { label: 'Workshops', value: 0, suffix: '+' },
  { label: 'Competitions', value: 2, suffix: '+' },
  { label: 'Awards', value: 0, suffix: '+' },
]
